import os

lines = [
'#!/usr/bin/env python3',
'"""',
'Phase 1 - Script 03',
'MODIS Aqua Chlorophyll-a and SST Download for Region R1',
'Region: Strait of Malacca (98-109E, 1-10N)',
'Uses NASA CMR search without authentication',
'Direct download with Earthdata token',
'"""',
'import sys',
'import requests',
'from pathlib import Path',
'sys.path.insert(0, str(Path(__file__).parent.parent.parent))',
'from utils import setup_logging, ensure_dir, load_config',
'setup_logging("03_download_modis_R1")',
'from loguru import logger',
'SEARCH_URL = "https://cmr.earthdata.nasa.gov/search/granules.json"',
'TOKEN_URL  = "https://urs.earthdata.nasa.gov/api/users/token"',
'CHUNK_SIZE = 8192',
'BBOX       = "98.0,1.0,109.0,10.0"',
'DATE_START = "2022-01-01"',
'DATE_END   = "2025-12-31"',
'PRODUCTS = [',
'    {"short_name": "MODISA_L3m_CHL", "subdir": "chlor_a", "label": "Chlorophyll-a"},',
'    {"short_name": "MODISA_L3m_SST", "subdir": "sst",     "label": "SST"},',
']',
'def get_token(username, password):',
'    try:',
'        resp = requests.get(',
'            "https://urs.earthdata.nasa.gov/api/users/tokens",',
'            auth=(username, password), timeout=30',
'        )',
'        if resp.status_code == 200:',
'            tokens = resp.json()',
'            if tokens:',
'                token = tokens[0]["access_token"]',
'                logger.success(f"NASA token obtained")',
'                return token',
'        resp2 = requests.post(',
'            "https://urs.earthdata.nasa.gov/api/users/token",',
'            auth=(username, password), timeout=30',
'        )',
'        if resp2.status_code == 200:',
'            token = resp2.json()["access_token"]',
'            logger.success(f"NASA token created")',
'            return token',
'        logger.error(f"Token failed: {resp2.status_code} {resp2.text[:100]}")',
'        return None',
'    except Exception as e:',
'        logger.error(f"Token error: {e}")',
'        return None',
'def search_granules(short_name, token):',
'    granules = []',
'    page = 1',
'    headers = {"Authorization": f"Bearer {token}"}',
'    while True:',
'        try:',
'            resp = requests.get(SEARCH_URL, params={',
'                "short_name":   short_name,',
'                "bounding_box": BBOX,',
'                "temporal":     f"{DATE_START}T00:00:00Z,{DATE_END}T23:59:59Z",',
'                "page_size":    200,',
'                "page_num":     page,',
'            }, headers=headers, timeout=60)',
'            if resp.status_code != 200:',
'                logger.error(f"Search error: {resp.status_code}")',
'                break',
'            entries = resp.json()["feed"]["entry"]',
'            if not entries:',
'                break',
'            granules.extend(entries)',
'            logger.info(f"  Found {len(granules)} granules...")',
'            if len(entries) < 200:',
'                break',
'            page += 1',
'        except Exception as e:',
'            logger.error(f"Search failed: {e}")',
'            break',
'    return granules',
'def download_file(url, out_path, token):',
'    if out_path.exists():',
'        return True',
'    headers = {"Authorization": f"Bearer {token}"}',
'    try:',
'        with requests.get(url, headers=headers,',
'                         stream=True, timeout=120) as r:',
'            r.raise_for_status()',
'            total = int(r.headers.get("Content-Length", 0))',
'            with open(out_path, "wb") as f:',
'                downloaded = 0',
'                for chunk in r.iter_content(CHUNK_SIZE):',
'                    f.write(chunk)',
'                    downloaded += len(chunk)',
'                    if total > 0:',
'                        pct = downloaded / total * 100',
'                        print(f"\\r    {pct:.0f}%", end="", flush=True)',
'            print()',
'        return True',
'    except Exception as e:',
'        logger.error(f"  Failed: {e}")',
'        if out_path.exists():',
'            out_path.unlink()',
'        return False',
'def main():',
'    config   = load_config()',
'    username = config.get("NASA_EARTHDATA_USERNAME", "")',
'    password = config.get("NASA_EARTHDATA_PASSWORD", "")',
'    out_root = ensure_dir(',
'        Path(config.get("MODIS_DIR", "outputs/modis")) / "R1"',
'    )',
'    logger.info("=" * 60)',
'    logger.info("Phase 1 - MODIS Download: Region R1 Strait of Malacca")',
'    logger.info(f"BBOX: {BBOX}")',
'    logger.info(f"Period: {DATE_START} to {DATE_END}")',
'    logger.info(f"Output: {out_root}")',
'    logger.info("=" * 60)',
'    token = get_token(username, password)',
'    if not token:',
'        logger.error("Cannot proceed without NASA token")',
'        sys.exit(1)',
'    for prod in PRODUCTS:',
'        out_dir = ensure_dir(out_root / prod["subdir"])',
'        logger.info(f"\\nProduct: {prod[\'label\']}")',
'        logger.info(f"Searching {prod[\'short_name\']}...")',
'        granules = search_granules(prod["short_name"], token)',
'        logger.info(f"Total found: {len(granules)}")',
'        ok = fail = skip = 0',
'        for i, g in enumerate(granules, 1):',
'            links = [',
'                l["href"] for l in g.get("links", [])',
'                if ".nc" in l.get("href", "")',
'                and "data#" in l.get("rel", "")',
'            ]',
'            if not links:',
'                skip += 1',
'                continue',
'            url      = links[0]',
'            fname    = url.split("/")[-1]',
'            out_path = out_dir / fname',
'            if out_path.exists():',
'                skip += 1',
'                continue',
'            logger.info(f"  [{i}/{len(granules)}] {fname}")',
'            if download_file(url, out_path, token):',
'                ok += 1',
'            else:',
'                fail += 1',
'        logger.info(f"  Result: {ok} downloaded, {fail} failed, {skip} skipped")',
'    logger.info("\\n" + "=" * 60)',
'    logger.info("MODIS R1 download complete")',
'    logger.info("=" * 60)',
'if __name__ == "__main__":',
'    main()',
]

os.makedirs("scripts/phase1_data", exist_ok=True)
with open("scripts/phase1_data/03_download_modis_R1.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("R1 MODIS download script written OK")
print(open("scripts/phase1_data/03_download_modis_R1.py", encoding="utf-8").read()[:200])