import os

lines = [
'#!/usr/bin/env python3',
'"""',
'Phase 1 - Script 02',
'CMEMS 3D Ocean Physics Download for Region R1',
'Downloads: 3D currents (U,V), temperature, salinity, MLD, Stokes drift',
'Product: GLORYS12v1 global 1/12 degree daily',
'Region: Strait of Malacca (98-109E, 1-10N)',
'Period: 2022-2025',
'Estimated size: ~12 GB',
'"""',
'import sys',
'from pathlib import Path',
'sys.path.insert(0, str(Path(__file__).parent.parent.parent))',
'from utils import setup_logging, ensure_dir, load_config, REGIONS',
'setup_logging("02_download_cmems_R1")',
'from loguru import logger',
'def download_physics(region, year, out_dir):',
'    import copernicusmarine as cm',
'    fname    = f"R1_physics_{year}.nc"',
'    out_path = out_dir / fname',
'    if out_path.exists():',
'        logger.info(f"  SKIP (exists): {fname}")',
'        return True',
'    logger.info(f"  Downloading physics: {fname}")',
'    try:',
'        cm.subset(',
'            dataset_id        = "cmems_mod_glo_phy_my_0.083deg_P1D-m",',
'            variables         = ["uo", "vo", "thetao", "so", "mlotst"],',
'            minimum_longitude = region["lon_min"],',
'            maximum_longitude = region["lon_max"],',
'            minimum_latitude  = region["lat_min"],',
'            maximum_latitude  = region["lat_max"],',
'            minimum_depth     = 0.5,',
'            maximum_depth     = 2000.0,',
'            start_datetime    = f"{year}-01-01T00:00:00",',
'            end_datetime      = f"{year}-12-31T23:59:59",',
'            output_directory  = str(out_dir),',
'            output_filename   = fname,',
'        )',
'        logger.success(f"  Done: {fname}")',
'        return True',
'    except Exception as e:',
'        logger.error(f"  Failed {fname}: {e}")',
'        return False',
'def download_waves(region, year, out_dir):',
'    import copernicusmarine as cm',
'    fname    = f"R1_waves_{year}.nc"',
'    out_path = out_dir / fname',
'    if out_path.exists():',
'        logger.info(f"  SKIP (exists): {fname}")',
'        return True',
'    logger.info(f"  Downloading waves: {fname}")',
'    try:',
'        cm.subset(',
'            dataset_id        = "cmems_mod_glo_wav_my_0.2deg_PT3H-i",',
'            variables         = ["VSDX", "VSDY"],',
'            minimum_longitude = region["lon_min"],',
'            maximum_longitude = region["lon_max"],',
'            minimum_latitude  = region["lat_min"],',
'            maximum_latitude  = region["lat_max"],',
'            start_datetime    = f"{year}-01-01T00:00:00",',
'            end_datetime      = f"{year}-12-31T23:59:59",',
'            output_directory  = str(out_dir),',
'            output_filename   = fname,',
'        )',
'        logger.success(f"  Done: {fname}")',
'        return True',
'    except Exception as e:',
'        logger.error(f"  Failed {fname}: {e}")',
'        return False',
'def main():',
'    config = load_config()',
'    region = REGIONS["R1"]',
'    years  = [2022, 2023, 2024, 2025]',
'    physics_dir = ensure_dir(',
'        Path(config.get("CMEMS_DIR", "outputs/cmems")) / "physics" / "R1"',
'    )',
'    waves_dir = ensure_dir(',
'        Path(config.get("CMEMS_DIR", "outputs/cmems")) / "waves" / "R1"',
'    )',
'    logger.info("=" * 60)',
'    logger.info("Phase 1 - CMEMS Download: Region R1 Strait of Malacca")',
'    logger.info(f"Longitude: {region[\'lon_min\']} to {region[\'lon_max\']}")',
'    logger.info(f"Latitude:  {region[\'lat_min\']} to {region[\'lat_max\']}")',
'    logger.info(f"Years:     {years}")',
'    logger.info(f"Depth:     0.5m to 2000m")',
'    logger.info("=" * 60)',
'    ok_p = fail_p = ok_w = fail_w = 0',
'    for year in years:',
'        logger.info(f"\\nYear {year}:")',
'        if download_physics(region, year, physics_dir):',
'            ok_p += 1',
'        else:',
'            fail_p += 1',
'        if download_waves(region, year, waves_dir):',
'            ok_w += 1',
'        else:',
'            fail_w += 1',
'    logger.info("\\n" + "=" * 60)',
'    logger.info("COMPLETE:")',
'    logger.info(f"  Physics: {ok_p} OK, {fail_p} failed")',
'    logger.info(f"  Waves:   {ok_w} OK, {fail_w} failed")',
'    logger.info("=" * 60)',
'if __name__ == "__main__":',
'    main()',
]

os.makedirs("scripts/phase1_data", exist_ok=True)
with open("scripts/phase1_data/02_download_cmems_R1.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("R1 CMEMS download script written OK")
print(open("scripts/phase1_data/02_download_cmems_R1.py", encoding="utf-8").read()[:200])